FROM openjdk:17-slim
LABEL org.label-schema.license="CC BY-NC-SA 4.0"

# Set working directory
WORKDIR /app

# Copy the JAR file into the container
COPY endpoints.jar /app
COPY cli.jar .

# Run the JAR file
CMD ["java", "-jar", "endpoints.jar"]
