FROM openjdk:17-slim
LABEL org.label-schema.license="CC BY-NC-SA 4.0"

# Set working directory
WORKDIR /app

# Copy the JAR file into the container
COPY client.jar /app

# Run the JAR file
CMD ["java", "-jar", "client.jar"]

