version: "3.9"
services:
  consumer:
    container_name: consumer_container
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      isDev: ${isDev}
      db_max_pool_size: ${db_max_pool_size}
      topic_name_tasks: ${topic_name_tasks}
      timer_threads_in_process: ${timer_threads_in_process}
      kafka_host: ${kafka_host}
      db_port: ${db_port}
      db_user: ${db_user}
      db_password: ${db_password}
      db_host: ${db_host}
      db_name: ${db_name}
      notifications_http_version: ${notifications_http_version}
    hostname: consumer
    networks:
      my_network:
        ipv4_address: 172.16.238.16
  redis-ui:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    networks:
      my_network:
        ipv4_address: 172.16.238.15
    environment:
      REDIS_HOST: ${REDIS_HOST}
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    hostname: redis
    networks:
      my_network:
        ipv4_address: 172.16.238.14
  postgres:
    container_name: my_postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      my_network:
        ipv4_address: 172.16.238.10
    hostname: postgres
    command: >
      postgres -c listen_addresses=*
  pgadmin:
    container_name: my_pgadmin
    build:
      context: .
      dockerfile: Dockerfile.pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      my_network:
        ipv4_address: 172.16.238.11
    hostname: pgadmin

  portainer:
    container_name: my_portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      my_network:
        ipv4_address: 172.16.238.12
    hostname: portainer

  endpoint:
    container_name: my_endpoint
    build:
      context: .
      dockerfile: Dockerfile.endpoints
    environment:
      isDev: ${isDev}
      db_max_pool_size: ${db_max_pool_size}
      topic_name_tasks: ${topic_name_tasks}
      timer_threads_in_process: ${timer_threads_in_process}
      kafka_host: ${kafka_host}
      db_port: ${db_port}
      db_user: ${db_user}
      db_password: ${db_password}
      db_host: ${db_host}
      db_name: ${db_name}
      minimum_interval_time: ${minimum_interval_time}
    ports:
      - "8080:8080"
    networks:
      my_network:
        ipv4_address: 172.16.238.13
    hostname: endpoints

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

volumes:
  postgres_data:
  portainer_data:
  redis_data:
